mod attendance;
pub(crate) mod attendance_events;
pub(crate) mod attendance_marks;
pub(crate) mod attendance_service;
mod calendar;
pub(crate) mod calendar_service;
pub mod excel;
#[cfg(target_os = "windows")]
mod excel_com;
pub(crate) mod excel_preview;
pub(crate) mod excel_service;
pub(crate) mod excel_service_helpers;
pub mod logic;
pub mod models;
mod naming;
mod preview;
pub(crate) mod progress;
pub mod repository;
pub(crate) mod roster;
pub(crate) mod roster_helpers;
pub(crate) mod roster_parser;
pub(crate) mod roster_sync;
pub(crate) mod roster_sync_learner;
pub mod service;
pub(crate) mod sf2_metadata;
pub(crate) mod template_create;
pub(crate) mod template_ops;
pub(crate) mod template_update;
mod validation;
pub(crate) mod validation_service;
mod workbook_files;
